from methods.weight_methods import (
    METHODS,
    MGDA,
    STL,
    LinearScalarization,
    NashMTL,
    PCGrad,
    Uncertainty,
    FairGrad,
    FAMO,
    NashMTL,
    ScaleInvariantLinearScalarization,
    LOG_MGDA,
    CAGrad,
    GradDrop,
    LOG_CAGrad,
    RLW,
    IMTLG,
    LOG_IMTLG,
    DynamicWeightAverage,
)

